### ISSUE TITLE
Error: 'wptomd-types' is not a registered wp command. See 'wp help' for available commands.

### ISSUE THREAD

**Issue by drhitchcockco** [joshcanhelp/wordpress-to-markdown#1]
## Expected Behavior
When I ran the code ```wp wptomd-types``` the content types in my website should have been displayed.

## Actual Behavior
After following the steps in the README I got the following error:
```
Error: 'wptomd-types' is not a registered wp command. See 'wp help' for available commands.
```

## Specifications
OS:	Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64
Shell:
PHP binary:	/usr/local/bin/php
PHP version:	7.3.11
php.ini used:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/docroot/wp-content/mu-plugins/wp-to-md
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.3.0

## Other info
I am running this on Docker on my local machine via Docksal but I had the same issue with this on my live/production server.

If there is any other info that would be helpful just holla 🙂

**Comment by joshcanhelp** [comment]
@starlifter-nz - Apologies for the best instructions! I just walked through the commands I have in the README and they are incorrect. The `wp-content/mu-plugins/wp-to-md.php` file should look like:

```php
<?php if ( class_exists( 'WP_CLI' ) ) require_once 'wp-to-md/wp-to-md.php';
```

... and you need to run `composer install` in the directory you cloned this repo into. Or, from the WP root directory:

```bash
❯ composer install -d wp-content/mu-plugins/wp-to-md
```

Just updated the README with all of this so you could also just delete what you've got and start from scratch 👍
